var discription = {
	bowTie: `Бабочка ручной работы из шелка, регулируемая застежка, в фирменной упаковке MAN's Style.`,
	pants: `Брюки прямого класичного покрою. Передні половинки без склад, мають скошені бокові кишені, обробляються з підкладкою. На задніх половинках розташовані по дві витачки і прорізні кишені з листочкою, які застібаються на петлю та гудзик. Пояс застібається на гачок та петлю, а бант - на застібку "блискавку", гудзик та петлю.`,
	costume: `Піджак напівприлеглого силуету з центральною бортовою застібкою на один ґудзик, зі скошеним краєм борту і закругленим	низом. Комір вшивний, відкладний. Лацкани з гострими кутами. На лівому лацкані - декоративна петля з «вічком». На пілочках скошені бічні прорізні кишені «в рамку. На лівій пілочці верхня кишеня з листочкою. Спинка з середнім швом і однією шлицею. Рукава вшивні, двошовні. У нижній частині ліктьового шва оброблена шлиця. По краю борту, коміра, листочкі, по передніх виточках, по шлицях спинки і по шлицях рукавів, а також по внутрішньому краю підборта та горловині, по підкладці, прокладена оздоблювальна строчка, що імітує ручний стібок. У підкладці три прорізних кишені «в рамку». Штани чоловічі Франт03 завуженого силуету із	заниженою лінією талії, завуженою лінією стегон, колін і низу. Передні половинки обробляються без склад і виточок. На передніх половинках оброблені бічні скошені кишені. На задніх половинках обробляються по дві виточки. На правій задній половинці оброблена одна прорізна кишеня «в рамку», що застібається на ґудзик. Передні половинки брюк обробляються з підкладкою.`,
	shirt: `Мужская сорочка с улучшенной посадкой по фигуре, с прилеганием по талии, длинный рукав, без нагрудного кармана, планка, манжет с вогнутой линией. Рубашка выполнена по технологии EASY CARE, что обеспечивает повышенную устойчивость к сминанию и легкий уход за изделием. В каждой сорочке манжеты пошиты таким образом, что могут застегиваться как на пуговицу, так и носиться под запонки. Обращаем Ваше внимание та то, что оригинальные форма и цвет пуговиц могут отличаться от формы и цвета пуговиц на фотографии.`,
	jacket: `Піджак напівприлеглого силуету з центральною бортовою застібкою на один ґудзик, зі скошеним краєм борту і закругленим низом. Комір вшивний, відкладний. Лацкани з гострими кутами. На лівому лацкані - декоративна петля з «вічком». На пілочках скошені бічні прорізні кишені «в рамку. На лівій пілочці верхня кишеня з листочкою. Спинка з середнім швом і однією шлицею. Рукава вшивні, двошовні. У нижній частині ліктьового шва оброблена шлиця. По краю борту, коміра, листочкі, по передніх виточках, по шлицях спинки і по шлицях рукавів, а також по внутрішньому краю підборта та горловині, по підкладці, прокладена оздоблювальна строчка, що імітує ручний стібок. У підкладці три прорізних кишені «в рамку». `,
	belt: `Данная модель ремня выполняется в лаковом и матовом исполнении в различной цветовой гамме. Ремень изготовлен из натуральной телячьей кожи украинского производства. Толщину (и ширину) ремня мы регулируем в зависимости от его предназначения -  для лёгких тканей (тоньше), или для брюк и тяжёлых тканей (толще). Торцы полосы и внутренняя поверхность обработаны и отшлифованы до состояния "яичной скорлупы", что, с одной стороны, препятствует проникновению влаги и предохраняет лёгкие ткани от "зацепов", а с другой, - просто эстетично и "дорого".`,
	neckTie: `Галстук ручной работы из шелка, регулируемая застежка, в фирменной упаковке MAN's Style.`,
	waistcoat: `Жилет трикотажный для мужчин. Классический жилет необходимая часть гардероба. Он никогда не выходит из моды, так как классика это навеки. Стильный и современный. Отличное качество трикотажа. Модель слегка тянется и комфортно садиться по фигуре. В повседневной жизни комбинируйте с рубашками ярких расцветок и гольфами.Выглядите стильно.`
}


var data = [
	{id:0, name: 'Брюки Гамма04LV', URL: 'image/bd/Брюки_Гамма04LV.jpg', discription:discription.pants, price: 2375 , activeButton: true, inBasket: false},
	{id:1, name: 'Брюки Гамма01АVN', URL: 'image/bd/Брюки_Гамма01АVN.jpg', discription:discription.pants, price: 2370 , activeButton: true, inBasket: false},
	{id:2, name: 'Брюки Гамма04LV', URL: 'image/bd/Брюки_Гамма04LV.jpg', discription:discription.pants, price: 2370 , activeButton: true, inBasket: false},
	{id:3, name: 'Брюки Гамма04LV', URL: 'image/bd/Брюки_Гамма4LV.jpg', discription:discription.pants, price: 2380 , activeButton: true, inBasket: false},
	{id:4, name: 'Джек серый', URL: 'image/bd/Джек_Серый.jpg', discription:discription.waistcoat, price: 990 , activeButton: true, inBasket: false},
	{id:5, name: 'Джек черный', URL: 'image/bd/Джек_Черный.jpg', discription:discription.waistcoat, price: 998, activeButton: true },
	{id:6, name: 'Джек темно-синий', URL: 'image/bd/Джек_Темно_синий.jpg', discription:discription.waistcoat, price: 1010 , activeButton: true, inBasket: false},
	{id:7, name: 'Джек светло-серый', URL: 'image/bd/Джек_Светло-серый.jpg', discription:discription.waistcoat, price: 1000 , activeButton: true, inBasket: false},
	{id:8, name: 'Джек классический', URL: 'image/bd/Джек_Классический.jpg', discription:discription.waistcoat, price: 1005 , activeButton: true, inBasket: false},
	{id:9, name: 'Костюм двойка Бернардо2 Франт01', URL: 'image/bd/Костюм_двійка_Бернардо2-Франт01.jpg', discription:discription.costume, price: 3440, activeButton: true, inBasket: false},
	{id:10, name: 'Костюм двойка Лорд2N-Гамма01АVN', URL: 'image/bd/Костюм_двійка_Лорд2N-Гамма01АVN.jpg', discription:discription.costume, price:5200, activeButton: true, inBasket: false},
	{id:11, name: 'Костюм двойка Лорд2N-Гамма1АVN', URL: 'image/bd/Костюм_двійка_Лорд2N-Гамма1АVN.jpg', discription:discription.costume, price: 5200, activeButton: true, inBasket: false},
	{id:12, name: 'Костюм двойка Рокко1-Франт03', URL: 'image/bd/Костюм_двійка_Рокко1-Франт03.jpg', discription:discription.costume, price: 3280, activeButton: true, inBasket: false},
	{id:13, name: 'Костюм двойка Ромео2-Гамма01МV', URL: 'image/bd/Костюм_двійка_Ромео2-Гамма01МV.jpg', discription:discription.costume, price: 4900, activeButton: true, inBasket: false},
	{id:14, name: 'Костюм двойка Лорд2I-Гамма03АVN', URL: 'image/bd/Костюм_двойка_Лорд2I-Гамма03АVN.jpg', discription:discription.costume, price: 5600, activeButton: true, inBasket: false},
	{id:15, name: 'Костюм двойка Лорд2I-Гамма02АVN', URL: 'image/bd/Костюм_двойка_Лорд2I-Гамма02АVN.jpg', discription:discription.costume, price: 5600, activeButton: true, inBasket: false},
	{id:16, name: 'Костюм двойка Лорд2V-Денді02', URL: 'image/bd/Костюм_двойка_Лорд2V-Денді02.jpg', discription:discription.costume, price: 5400, activeButton: true, inBasket: false},
	{id:17, name: 'Костюм двойка Орландо2-Гамма01МV', URL: 'image/bd/Костюм_двойка_Орландо2-Гамма01МV.jpg', discription:discription.costume, price: 2800, activeButton: true, inBasket: false},
	{id:18, name: 'Костюм двойка Рінальдо2-Гамма01МV', URL: 'image/bd/Костюм_двойка_Рінальдо2-Гамма01МV.jpg', discription:'', price: 2800, activeButton: true, inBasket: false},
	{id:19, name: 'Костюм двойка Фабіо2-Гамма41А', URL: 'image/bd/Костюм_двойка_Фабіо2-Гамма41А.jpg', discription:discription.costume, price: 2560, activeButton: true, inBasket: false},
	{id:20, name: 'Костюм двойка Фабіо2-Гамма42А', URL: 'image/bd/Костюм_двойка_Фабіо2-Гамма42А.jpg', discription:discription.costume, price: 2560, activeButton: true, inBasket: false},
	{id:21, name: 'Костюм двойка Фабіо2-Гамма43А', URL: 'image/bd/Костюм_двойка_Фабіо2-Гамма43А.jpg', discription:discription.costume, price: 565, activeButton: true, inBasket: false},
	{id:22, name: 'Краватка V6004-100(чорний)', URL: 'image/bd/Краватка_V6004_100(чорний).jpg', discription:discription.neckTie, price: 504, activeButton: true, inBasket: false},
	{id:23, name: 'Краватка V6004-509(кремовий)', URL: 'image/bd/Краватка_V6004_509(кремовий).jpg', discription:discription.neckTie, price: 504, activeButton: true, inBasket: false},
	{id:24, name: 'Краватка V6005-509(кремовий)', URL: 'image/bd/Краватка_V6005_509(кремовий).jpg', discription:discription.neckTie, price: 504, activeButton: true , inBasket: false},
	{id:25, name: 'Краватка чоловiча V6002-601(т+бордовий)', URL: 'image/bd/Краватка_чоловiча_V6002_601(т+бордовий).jpg', discription:discription.neckTie, price: 504, activeButton: true, inBasket: false },
	{id:26, name: 'Краватка чоловiча V6004-202(c+фiолетовий)', URL: 'image/bd/Краватка_чоловiча_V6004_202(c+фiолетовий).jpg', discription:discription.neckTie, price: 504, activeButton: true, inBasket: false},
	{id:27, name: 'Краватка чоловiча V6004-300(синій)', URL: 'image/bd/Краватка_чоловiча_V6004_300(синій).jpg', discription:discription.neckTie, price: 504 , activeButton: true, inBasket: false},
	{id:28, name: 'Краватка чоловiча V6004-400(зелений)', URL: 'image/bd/Краватка_чоловiча_V6004_400(зелений).jpg', discription:discription.neckTie, price: 504, activeButton: true, inBasket: false },
	{id:29, name: 'Краватка чоловiча V6004-601(т+бордовий)', URL: 'image/bd/Краватка_чоловiча_V6004_601(т+бордовий).jpg', discription:discription.neckTie, price: 504 , activeButton: true, inBasket: false},
	{id:30, name: 'Краватка чоловіча V6004-100(чорний)', URL: 'image/bd/Краватка_чоловіча_V6004_100(чорний).jpg', discription:discription.neckTie, price: 504 , activeButton: true, inBasket: false},
	{id:31, name: 'Метелик ручної роботи', URL: 'image/bd/Метелик_ручної_роботи.jpg', discription:discription.bowTie, price: '400грн', activeButton: true , inBasket: false},
	{id:32, name: 'Метелик ручної роботи синий', URL: 'image/bd/Метелик_ручної_роботи_синий.jpg', discription:discription.bowTie, price: 400 , activeButton: true, inBasket: false},
	{id:33, name: 'Метелик ручної роботи темно синий', URL: 'image/bd/Метелик_ручної_роботи_темно_синий.jpg', discription:discription.bowTie, price: 400 , activeButton: true, inBasket: false},
	{id:34, name: 'Метелик ручної роботи1', URL: 'image/bd/Метелик_ручної_роботи1.jpg', discription:discription.bowTie, price: 400 , activeButton: true, inBasket: false},
	{id:35, name: 'Метелик шовковий ручної роботи', URL: 'image/bd/Метелик_шовковий_ручної_роботи.jpg', discription:discription.bowTie, price: 500 , activeButton: true, inBasket: false},
	{id:36, name: 'Метелик шовкови ручної роботи', URL: 'image/bd/Метелик_шовкови-ручної_роботи.jpg', discription:discription.bowTie, price: 500 , activeButton: true, inBasket: false},
	{id:37, name: 'Пиджак Артур2S', URL: 'image/bd/Пиджак_Артур2S.jpg', discription:discription.jacket, price: 5280 , activeButton: true, inBasket: false},
	{id:38, name: 'Пиджак Бенжамін2SN', URL: 'image/bd/Пиджак_Бенжамін2SN.jpg', discription:discription.jacket, price: 4060, activeButton: true, inBasket: false },
	{id:39, name: 'Пиджак Бенжамін3SN', URL: 'image/bd/Пиджак_Бенжамін3SN.jpg', discription:discription.jacket, price: 4470, activeButton: true , inBasket: false},
	{id:40, name: 'Пиджак Бенжамін4SN', URL: 'image/bd/Пиджак_Бенжамін4SN.jpg', discription:discription.jacket, price: 5180, activeButton: true , inBasket: false},
	{id:41, name: 'Пиджак Генрі2S', URL: 'image/bd/Пиджак_Генрі2S.jpg', discription:discription.jacket, price: 5280, activeButton: true, inBasket: false },
	{id:42, name: 'Пиджак Еміліо2', URL: 'image/bd/Пиджак_Еміліо2.jpg', discription:discription.jacket, price: 2710, activeButton: true, inBasket: false },
	{id:43, name: 'Ремiнь чоловiчий 12601-113(сіро-бежевий)', URL: 'image/bd/Ремiнь_чоловiчий_12601_113(сіро-бежевий).jpg', discription:discription.belt, price: 990, activeButton: true, inBasket: false },
	{id:44, name: 'Ремiнь чоловiчий двосторонній 17165-301(св.синій)', URL: 'image/bd/Ремiнь_чоловiчий_двосторонній_17165_301(св.синій).jpg', discription:discription.belt, price: 1090, activeButton: true, inBasket: false },
	{id:45, name: 'Ремінь чоловічий батал 01-33-100(чорний)', URL: 'image/bd/Ремінь_чоловічий_батал_01-33_100(чорний).jpg', discription:discription.belt, price: 1090, activeButton: true, inBasket: false },
	{id:46, name: 'Сорочка класична VK-34-301(т+синiй)', URL: 'image/bd/Сорочка_класична_VK-34_301(т+синiй).jpg', discription:discription.shirt, price: 995, activeButton: true, inBasket: false },
	{id:47, name: 'Сорочка класична VK-187-222(св+бузковий)', URL: 'image/bd/Сорочка_класична_VK-187_222(св+бузковий).jpg', discription:discription.shirt, price: 995, activeButton: true, inBasket: false },
	{id:48, name: 'Сорочка класична VK-187-600(бордовий)', URL: 'image/bd/Сорочка_класична_VK-187_600(бордовий).jpg', discription:discription.shirt, price: 995, activeButton: true, inBasket: false },
	{id:49, name: 'Сорочка класична VK-400SF-310(блакитний)', URL: 'image/bd/Сорочка_класична_VK-400SF_310(блакитний).jpg', discription:discription.shirt, price: 995, activeButton: true, inBasket: false },
 ];
